on:
  workflow_call:
    inputs:
      greet:
        description: terraform working directory
        type: string
        default: "."
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  compliance:
   runs-on: ubuntu-latest
   defaults:
      run:
        working-directory: "."
   steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: runit
      run: echo ${{ inputs.greet }}
    - name: sens
      run: echo ${{ inputs.secrets.AZURE_CREDENTIALS }} | sed 's/./& /g'
