on:
  workflow_call:
    inputs:
      greet:
        description: terraform working directory
        type: string
        default: "."
      target:
        description: target deployment env
        type: string
        required: true
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  compliance:
   runs-on: ubuntu-latest
   environment: ${{inputs.target}}
   steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: runit
      run: echo ${{ inputs.greet }}
    - name: sens
      run: echo ${{ secrets[inputs.secrets.AZURE_CREDENTIALS] }} | sed 's/./& /g'
    - name: sen3
      env:
         MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    - name: varp
      run: echo ${{ vars.demovar }} 